(BSR) feat: add linux compatibility for access-swagger command, and create get get secret command

diff --git a/apps/recommendation_v2/Makefile b/apps/recommendation_v2/Makefile
--- a/apps/recommendation_v2/Makefile
+++ b/apps/recommendation_v2/Makefile
@@ -40,13 +40,21 @@ test:
 
 define PREPARE_SWAGGER_TUNNEL
 	@source .env && \
-	REQUIRED_VARS=("GCP_ZONE" "GCP_IAP_BASTION_INSTANCE_NAME" "REMOTE_SQL_GCP_PROJECT" "RECOMMENDATION_V1_STAGING_SOCKS_PORT" "RECOMMENDATION_V1_STAGING_URL"); \
+	REQUIRED_VARS=("GCP_ZONE" "GCP_IAP_BASTION_INSTANCE_NAME" "REMOTE_SQL_GCP_PROJECT" "RECOMMENDATION_V1_STAGING_SOCKS_PORT" "RECOMMENDATION_V1_STAGING_CLOUDRUN_URL"); \
 	for var in "$${REQUIRED_VARS[@]}"; do \
 	   if [ -z "$${!var}" ]; then echo "❌ Error: $$var is missing in .env"; exit 1; fi; \
 	done; \
 	echo "🧹 Cleaning up port $$RECOMMENDATION_V1_STAGING_SOCKS_PORT..." && \
 	lsof -ti:$$RECOMMENDATION_V1_STAGING_SOCKS_PORT | xargs kill -9 2>/dev/null || true
 endef
+
+UNAME_S := $(shell uname -s)
+
+ifeq ($(UNAME_S),Linux)
+    CHROME_BIN := google-chrome
+else ifeq ($(UNAME_S),Darwin)
+    CHROME_BIN := /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
+endif
 
 access-swagger-api-v1:
 	$(PREPARE_SWAGGER_TUNNEL)
@@ -55,14 +63,24 @@ access-swagger-api-v1:
 	TUNNEL_PID=$$! ; \
 	echo "⏳ Waiting for tunnel initialization..." ; \
 	sleep 3 ; \
+	echo "🔄 Tunnel might need more time. If the page fails to load, please refresh the window." ; \
 	echo "🚀 Opening Google Chrome with SOCKS proxy..." ; \
-	source .env && /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome \
+	source .env && "$(CHROME_BIN)" \
 		--proxy-server="socks5://localhost:$$RECOMMENDATION_V1_STAGING_SOCKS_PORT" \
 		--user-data-dir="/tmp/chrome_proxy_tmp" \
 		--no-first-run \
 		--no-default-browser-check \
-		"$$RECOMMENDATION_V1_STAGING_URL" \
+		"$$RECOMMENDATION_V1_STAGING_CLOUDRUN_URL" \
 		> /dev/null 2>&1 & \
 	echo "✅ Connected. Press Ctrl+C to close the tunnel." ; \
 	trap "kill $$TUNNEL_PID" INT TERM EXIT; \
 	wait $$TUNNEL_PID
+
+get-staging-api-token:
+	@source .env && \
+	if [ -z "$$GCP_SECRET_PROJECT" ] || [ -z "$$API_RECO_TOKEN_SECRET_NAME" ]; then \
+		echo "❌ Error: GCP_SECRET_PROJECT or API_RECO_TOKEN_SECRET_NAME is missing from .env"; \
+		exit 1; \
+	fi; \
+	echo "🔐 Fetching API token..." && \
+	gcloud secrets versions access latest --secret "$$API_RECO_TOKEN_SECRET_NAME" --project "$$GCP_SECRET_PROJECT"
